# This workflow will generate the living documentation
# For more information see: https://github.com/prmiguel/docker-pickles

name: Pickles Living Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  living-documentation:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker://ghcr.io/prmiguel/docker-pickles:v3.0.1
      with:
        args: >-
          --feature-directory=./src/test/resources/features
          --output-directory=./report
          -df=dhtml
    - uses: actions/upload-artifact@v3
      with:
        name: pickles
        path: report/
    - name: Publish
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: pickles-pages
        folder: report/
